#!/usr/bin/env bash

echo "$PWD"

get_url() {
  local REMOTE
  REMOTE=$(git remote | grep "^${1:-origin}$")

  if [ -n "$REMOTE" ]; then
    git config --local --get "remote.$REMOTE.url"
  fi
}

get_domain() {
  local HOST

  if [[ "$1" =~ ^.*@([A-Za-z0-9\.]+):.*$ ]] || [[ "$1" =~ ^.*//([A-Za-z0-9\.]+)/.*$ ]]; then
    HOST="${BASH_REMATCH[1]}"
  fi

  echo "${HOST,,}"
}

main() {
  if [ "$1" = "0000000000000000000000000000000000000000" ]; then
    local HOST
    HOST=$(get_domain "$(get_url origin)")

    if [ -n "$HOST" ]; then
      local U

      for U in "${GIT_HOSTS_USERS[@]}"; do
        if echo "$U" | grep -E "^$HOST," 1>/dev/null 2>&1; then
          local SEGMENTS
          IFS="," read -r -a SEGMENTS <<< "$U"

          if [ -n "${SEGMENTS[1]}" ]; then
            echo "Set Email: ${SEGMENTS[1]}"
            git config --local user.email "${SEGMENTS[1]}"
          fi

          if [ -n "${SEGMENTS[2]}" ]; then
            echo "Set User: ${SEGMENTS[2]}"
            git config --local user.name "${SEGMENTS[2]}"
          fi
        fi
      done
    fi
  fi
}

main "$@"
