box = ENV["VAGRANT_DEFAULT_BOX"] || "fedora/35-cloud-base"

Vagrant.configure("2") do |config|
  config.env.enable
  config.timezone.value = :host
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "podman" do |podman|
    podman.vm.box = box

    podman.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-podman"
      vb.memory = "1024"
    end

    podman.vm.network "private_network", ip: "192.168.56.1"

    podman.vm.provision "shell", inline: <<-SHELL
      dnf install -y virtualbox-guest-additions
      dnf install -y podman

      groupadd -f -r podman

      #systemctl edit podman.socket
      mkdir -p /etc/systemd/system/podman.socket.d
      cat >/etc/systemd/system/podman.socket.d/override.conf <<EOF
[Socket]
SocketMode=0660
SocketUser=root
SocketGroup=podman
EOF
      systemctl daemon-reload
      echo "d /run/podman 0770 root podman" > /etc/tmpfiles.d/podman.conf
      sudo systemd-tmpfiles --create

      systemctl enable podman.socket
      systemctl start podman.socket

      usermod -aG podman $SUDO_USER
    SHELL
  end
end
