windowsBox = ENV["VAGRANT_WINDOWS_BOX"] || "gusztavvargadr/windows-11"

Vagrant.configure("2") do |config|
  config.env.enable
  config.timezone.value = :host
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "windows" do |windows|
    windows.vm.box = windowsBox

    windows.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-windows"
      vb.memory = "4096"
    end

    windows.vm.network "private_network", ip: "192.168.56.200"
  end
end
