macOSBox = ENV["VAGRANT_MACOS_BOX"] || "jhcook/macos-sierra"
windowsBox = ENV["VAGRANT_WINDOWS_BOX"] || "gusztavvargadr/windows-11"

Vagrant.configure("2") do |config|
  config.env.enable
  config.timezone.value = :host
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "macOS" do |macOS|
    macOS.vm.box = macOSBox

    macOS.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-macOS"
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--vram", "256"]
      vb.customize ["setextradata", :id, "VBoxInternal2/EfiGraphicsResolution", "1920x1080"]
    end

    macOS.vm.network "private_network", ip: "192.168.56.200"
  end

  config.vm.define "windows" do |windows|
    windows.vm.box = windowsBox

    windows.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-windows"
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--vram", "256"]
    end

    windows.vm.network "private_network", ip: "192.168.56.201"
  end
end
