#=======================================================================#
# Taps                                                                  #
#=======================================================================#

# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"

#=======================================================================#
# App Store                                                             #
#=======================================================================#

# Xcode
mas "Xcode", id: 497799835

# Keynote, Numbers, Pages
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541

# Others
mas "Microsoft To Do", id: 1274495053
mas "Amphetamine", id: 937984704

#=======================================================================#
# Casks                                                                 #
#=======================================================================#
cask_args no_quarantine: true

# Terminal
cask "iterm2"

# Browser
cask "google-chrome"
cask "firefox"
cask "microsoft-edge"
# cask "tor-browser"

# Editor
cask "visual-studio-code"
# cask "atom"
# cask "boostnote"
# cask "mathpix-snipping-tool"

# Git
# cask "fork"
# cask "sourcetree"
# cask "github"

# IM
# cask "aliwangwang"
cask "wechat"
# cask "qq"
cask "slack"

# Work
cask "wechatwork"
# cask "dingtalk"

# Music
cask "qqmusic"
cask "neteasemusic"

# Proxy
# cask "lantern"
cask "v2rayu"
cask "qv2ray"
# cask "shadowsocksx-ng"
# cask "openvpn-connect"
# cask "tunnelblick"

# Dev Tools
# cask "insomnia"
# cask "postman"
# cask "wireshark"
# cask "sequel-ace"
# cask "sequel-pro"
# cask "dash"
# cask "wechatwebdevtools"
# cask "switchhosts"

# Menu Bar
# cask "itsycal"
# cask "bitbar"

# Containers & Kubernetes
cask "docker"
cask "podman-desktop"

# Video Player
# cask "mpv"
# cask "iina"

# Audio Player
# cask "vox"

# Others
# cask "appcleaner"
# cask "blurred"

# Compression
cask "the-unarchiver"

# Productivity
# cask "alfred"
cask "rectangle"
cask "cheatsheet"

# Display
cask "monitorcontrol"
# cask "lunar"

# Settings
# cask "onyx"

# Screen Recorder
# cask "kap"

# Adobe
# cask "adobe-creative-cloud"
# cask "adobe-creative-cloud-cleaner-tool"

# Android
cask "android-studio"

# Flutter
cask "flutter"

# Julia
# cask "julia"

# Virtual Machine
cask "virtualbox"
cask "vagrant"

# Office
# cask "microsoft-office"

# Fonts
cask "font-meslo-lg-nerd-font"

#=======================================================================#
# Formulae                                                              #
#=======================================================================#

# Mac App Store
brew "mas"

# Touch ID
brew "pam-reattach"

# Shell
brew "bash"
brew "zsh"
brew "zplug"
# brew "fish"

# Pager
brew "less"

# Git
brew "git"
brew "git-filter-repo"
# brew "git-flow"
brew "git-flow-avh"
brew "git-lfs"
brew "git-extras"

# GitHub
# brew "gh"
# brew "hub"
brew "act"

# GitLab
# brew "glab"
# brew "lab"

# Editor
brew "vim"
brew "neovim"
# brew "bat"

# Multiplexer
brew "tmux"
brew "screen"

# Network Tools
brew "httpie"
brew "curl"
brew "wget"
brew "socat"
brew "mtr"

# Text Finder
brew "ack"
brew "the_silver_searcher"

# Fuzzy Finder
brew "fzf"

# Navigation
brew "autojump"
brew "z"

# Virtual Machine
brew "qemu"
brew "lima"

# Database
brew "mysql"
brew "postgresql"

# JSON
brew "jq"

# HTML
brew "recode"

# Command Correction
brew "thefuck"

# Defaults
brew "duti"

# Proxy
# brew "xray"
# brew "trojan-gfw/homebrew-trojan/trojan"
brew "mitmproxy"

# Encryption
brew "gnupg"

# Infrastructure
brew "hashicorp/tap/terraform"
brew "opentofu"
brew "pulumi"

# Containers & Kubernetes
# brew "docker"
# brew "docker-compose"
brew "podman"
brew "skopeo"
brew "dive"
brew "kubernetes-cli"
brew "helm"
brew "kind"
brew "minikube"
# brew "kubectx"
# brew "kubeseal"
brew "colima"

# Ctags
brew "ctags"

# Version Manager
brew "asdf"

# Shell Script
brew "shellcheck"
brew "shfmt"
brew "bats-core"

# Node
brew "node"
brew "nodenv"
brew "nodenv/nodenv/node-build-update-defs"
brew "nodenv/nodenv/nodenv-npm-migrate"
brew "nodenv/nodenv/nodenv-nvmrc"
brew "nodenv/nodenv/nodenv-package-json-engine"
brew "manlao/tap/node-build-aliases"
brew "manlao/tap/nodenv-auto-install"

# Deno
# brew "deno"

# Bun
brew "oven-sh/bun/bun"

# Dart
# brew "dart"

# Python
brew "python"
brew "pipx"
brew "pyenv"
brew "pyenv-pip-migrate"

# Ruby
brew "ruby"
brew "rbenv"
brew "cocoapods"

# Java
# brew "openjdk"
brew "jenv"

# Rust
brew "rustup-init"
# brew "rust"

# Go
brew "go"
brew "goenv"

# PHP
# brew "php"

# Kotlin
# brew "kotlin"

# Scala
# brew "scala"

# Dev Tools
brew "watchman"
